//
//  TipskiIcons.swift
//  Tipski
//
//  Created by Paul A Wood III on 10/14/16.
//  Copyright (c) 2016 Paul A Wood III. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class TipskiIcons : NSObject {

    //// Cache

    private struct Cache {
        static let black: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        static let backgroundColor: UIColor = UIColor(red: 0.212, green: 0.224, blue: 0.318, alpha: 1.000)
        static let backgroundLighter1: UIColor = UIColor(red: 0.290, green: 0.310, blue: 0.439, alpha: 1.000)
        static let backgroundLighter2: UIColor = UIColor(red: 0.435, green: 0.459, blue: 0.627, alpha: 1.000)
        static let foreground1: UIColor = UIColor(red: 0.596, green: 0.616, blue: 0.733, alpha: 1.000)
        static let foreground2: UIColor = UIColor(red: 0.757, green: 0.769, blue: 0.839, alpha: 1.000)
        static let foreground3: UIColor = UIColor(red: 0.878, green: 0.882, blue: 0.918, alpha: 1.000)
        static let foreground4: UIColor = UIColor(red: 0.957, green: 0.957, blue: 0.973, alpha: 1.000)
        static let redHighlight: UIColor = UIColor(red: 0.863, green: 0.333, blue: 0.384, alpha: 1.000)
        static let red: UIColor = UIColor(red: 0.776, green: 0.298, blue: 0.345, alpha: 1.000)
        static let orangeHighlight: UIColor = UIColor(red: 0.980, green: 0.616, blue: 0.298, alpha: 1.000)
        static let orange: UIColor = UIColor(red: 0.882, green: 0.553, blue: 0.267, alpha: 1.000)
        static let greenHighlight: UIColor = UIColor(red: 0.694, green: 0.737, blue: 0.224, alpha: 1.000)
        static let green: UIColor = UIColor(red: 0.624, green: 0.663, blue: 0.200, alpha: 1.000)
        static let blue: UIColor = UIColor(red: 0.200, green: 0.498, blue: 0.800, alpha: 1.000)
        static let blueHighlight: UIColor = UIColor(red: 0.224, green: 0.553, blue: 0.890, alpha: 1.000)
        static let purple: UIColor = UIColor(red: 0.502, green: 0.325, blue: 0.745, alpha: 1.000)
        static let purpleHighlight: UIColor = UIColor(red: 0.557, green: 0.361, blue: 0.831, alpha: 1.000)
    }

    //// Colors

    public class var black: UIColor { return Cache.black }
    public class var backgroundColor: UIColor { return Cache.backgroundColor }
    public class var backgroundLighter1: UIColor { return Cache.backgroundLighter1 }
    public class var backgroundLighter2: UIColor { return Cache.backgroundLighter2 }
    public class var foreground1: UIColor { return Cache.foreground1 }
    public class var foreground2: UIColor { return Cache.foreground2 }
    public class var foreground3: UIColor { return Cache.foreground3 }
    public class var foreground4: UIColor { return Cache.foreground4 }
    public class var redHighlight: UIColor { return Cache.redHighlight }
    public class var red: UIColor { return Cache.red }
    public class var orangeHighlight: UIColor { return Cache.orangeHighlight }
    public class var orange: UIColor { return Cache.orange }
    public class var greenHighlight: UIColor { return Cache.greenHighlight }
    public class var green: UIColor { return Cache.green }
    public class var blue: UIColor { return Cache.blue }
    public class var blueHighlight: UIColor { return Cache.blueHighlight }
    public class var purple: UIColor { return Cache.purple }
    public class var purpleHighlight: UIColor { return Cache.purpleHighlight }

}
